name: 06 Basics Context

on: 
  workflow_dispatch

jobs:
  print-context-data:
    runs-on: ubuntu-latest
    steps:
      - name: Print Context Data
        # run: echo ${{ github }}
        # run: echo ${{ github.actor }}
        run: echo ${{ github.event_name }}
