name: 08 Basics Variables
run-name: ${{ github.actor }} Explaining Variables - Try Number ${{ github.run_number }}

env:
  # NAME: value
  MY_NAME: 'Mahmoud Anwar'

on: 
  workflow_dispatch

jobs:
  print-variables:
    runs-on: ubuntu-latest
    env:
      MY_NAME2: 'Mahmoud Anwar 2'
    steps:
      - name: Print Variables
        env:
           MY_NAME3: 'Mahmoud Anwar 3'
        # run: echo $MY_NAME
        run: echo ${{ env.MY_NAME }}
      
      - name: Print Variables 2
        run: echo ${{ env.MY_NAME2 }}

  print-variables2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Variables 2
        run: echo ${{ vars.MY_CONFIG_VALUE }}
