name: 08 Basics Variables
run-name: ${{ github.actor }} Explaining Variables - Try Number ${{ github.run_number }}

env:
  KEY: value
  MY_NAME: 'Mahmoud Anwar'  

on: 
  workflow_dispatch

jobs:
  print-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Print Variables
        run: echo $MY_NAME
