name: 11 Basics Expressions
run-name: ${{ github.actor }} Explaining Expressions - Try Number ${{ github.run_number }}

env: 
  RUN_NUMBER: ${{ github.run_number }}

on: 
  workflow_dispatch

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"