name: 11 Basics Expressions
run-name: ${{ github.actor }} Explaining Expressions - Try Number ${{ github.run_number }}

env: 
  RUN_NUMBER: ${{ github.run_number > 1 && 'greater than 1' || 'less than 1' }}
  TESTING_VALUE: ${{ contains('Hello Wolrd', 'Wor') }}

on: 
  workflow_dispatch

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        # run: echo ${{ env.RUN_NUMBER }}
        # run: echo ${{ env.TESTING_VALUE }}
        run: exit 1
      
      - name: Print Hello World 2
        if: ${{ failure() }}
        run: echo ${{ env.TESTING_VALUE }}
