name: 16 Basics Marketplace
run-name: ${{ github.actor }} Explaining Marketplace - Try Number ${{ github.run_number }}

on: 
  workflow_dispatch

jobs:
  php-version:
    runs-on: ubuntu-latest
    steps:
      - name: Setup php version 7.2
        uses: nanasess/setup-php@v4
        with:
          php-version: '7.2'

      - name: Check PHP Version
        run: php -v
