name: 18 Basics Services
run-name: ${{ github.actor }} Explaining Services - Try Number ${{ github.run_number }}

on: 
  workflow_dispatch

jobs:
  php-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check PHP Version
        run: php -v
