name: 18 Basics Services
run-name: ${{ github.actor }} Explaining Services - Try Number ${{ github.run_number }}

on: 
  workflow_dispatch

jobs:
  redis-job:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest

    steps:
      - name: Install redis CLI
        run: sudo apt-get install -y redis
      
      - name: Check redis connection
        run: redis-cli ping
