name: 19 Basics Services - Alternative
run-name: ${{ github.actor }} Explaining Services - Try Number ${{ github.run_number }}

on: 
  workflow_dispatch

jobs:
  redis-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install redis CLI
        run: sudo apt-get install -y redis
      
      - name: Check redis connection
        run: redis-cli ping
