name: 20 Basics Custom Actions
run-name: ${{ github.actor }} Explaining Custom Actions - Try Number ${{ github.run_number }}

on: 
  workflow_dispatch

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello World
        run: echo "Hello World"
