name: 21 Basics Custom Actions 2
run-name: ${{ github.actor }} Explaining Custom Actions 2 - Try Number ${{ github.run_number }}

on: 
  workflow_dispatch

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4.2.2

      - name: Echo Hello World
        uses: ./.github/actions/print-hello-world
