name: 22 Basics github cli
run-name: ${{ github.actor }} Explaining github cli - Try Number ${{ github.run_number }}

on: 
  workflow_dispatch

jobs:
  open-new-issue-job:
    runs-on: ubuntu-latest
    steps:
      - name: Open New Issue
        run: gh issue create --title "New Issue Feon Gitub Actions" --body "Nothing works"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
