name: Example 01 - Commenting on PR
run-name: Example 01 - Commenting on PR

on: 
  pull_request:
    types: 
      - closed

jobs:
  comment-on-pr-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: comment on PR
        if: github.event.pull_request.merged == true
        run: gh pr comment $PR_NUMBER --body "We will not be merging you PR. Please update your code to satisfy our requirements and open a new PR."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
