name: Example 04 - run tests using predefined mysql
run-name: Example 04 - run tests using predefined mysql

on: 
  # pull_request
  workflow_dispatch

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      # - name: Install PHP & Composer (IF YOU WANT)
      
      - name: Enable MySQL
        run: sudo systemctl start mysql.service

      - name: Install project dependencies
        run: composer install -q
      
      - name: Prepare project
        run: |
          cp .env.example .env
          php artisan key:generate
      
      - name: Run tests
        run: php artisan test --compact





